name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: aim-hi-383318

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy deleteasset \
            --runtime python311 \
            --trigger-http \
            --entry-point main \
            --source . \
            --allow-unauthenticated