name: Deploy to Google Cloud Functions

on:
  push:
    paths:
      - main.py
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: YOUR_PROJECT_ID

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy deleteasset \
            --runtime python311 \
            --trigger-http \
            --entry-point main \
            --source . \
            --allow-unauthenticated